name: Keep Render Awake

on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: curl -s https://evo-backend-5dm0.onrender.com/api/health
